version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway/
    ports:
      - "8080:8080"

  retrieval-service:
    build:
      context: ./retrieval-service/
    ports:
      - "8000:8000"

  auth-service:
    build:
      context: ./auth-service/
    ports:
      - "8001:8001"

  playback-service:
    build:
      context: ./playback-service/
    ports:
      - "8002:8002"

  redis:
    image: redis
    ports:
      - "6379:6379"

  quick-discover-ui:
    build:
      context: ./spotify-quick-discover-frontend/
    ports:
      - "3000:3000"
