apiVersion: v1
kind: Service
metadata:
  name: playback-service
spec:
  selector:
    app: playback-service
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playback-service
spec:
  selector:
    matchLabels:
      app: playback-service
  template:
    metadata:
      labels:
        app: playback-service
    spec:
      containers:
        - name: playback-service
          image: mborhi/spotify-quick-discover-playback-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8002
