apiVersion: v1
kind: Service
metadata:
  name: retrieval-service
spec:
  type: NodePort
  selector:
    app: retrieval-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-service
spec:
  selector:
    matchLabels:
      app: retrieval-service
  template:
    metadata:
      labels:
        app: retrieval-service
    spec:
      containers:
        - name: retrieval-service
          image: mborhi/spotify-quick-discover-retrieval-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
