apiVersion: v1
kind: Service
metadata:
  name: quick-discover-ui
spec:
  selector:
    app: quick-discover-ui
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-discover-ui
spec:
  selector:
    matchLabels:
      app: quick-discover-ui
  template:
    metadata:
      labels:
        app: quick-discover-ui
    spec:
      containers:
        - name: quick-discover-ui
          image: mborhi/spotify-quick-discover/quick-discover-ui
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
